
enum AssessmentEnum {
  PROPOSAL_PRESENTATION = 'PROPOSAL_PRESENTATION',
  PROGRESS_REPORT = 'PROGRESS_REPORT',
  AVDISOR_ASSESSMENT = 'AVDISOR_ASSESSMENT',
  FINAL_REPORT = 'FINAL_REPORT',
  FINAL_PRESENTATION = 'FINAL_PRESENTATION',
}

export default AssessmentEnum;