name: GitHub Actions Demo
run-name: ${{ github.actor }} is trying to merge a pull request
on: [pull_request]

jobs:
  Build-and-Test-React-App:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you want to use
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Run Tests
        run: npm test
      - uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: build