name: GitHub Actions Demo
run-name: ${{ github.actor }} is trying to merge a pull request
on: [pull_request]

jobs:
  Build-and-Test-React-App:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Run Tests
        run: npm install --save-dev @testing-library/react @testing-library/jest-dom @testing-library/user-event & npm test